import { useQuery } from "@tanstack/react-query";
import React from "react";
import { BiLeftArrow } from "react-icons/bi";
import { Platform } from "../../interface";
import fetchData from "../../rawg/fetchData";
import Body from "../components/Body";
import PlatformCard from "../components/PlatformCard";
import { motion } from "framer-motion";
import { useRouter } from "next/router";
import { v4 } from "uuid";
import Head from "next/head";
import useMediaQuery from "../../hooks/useMediaQuery";
const PlatformsPage = () => {
  const router = useRouter();
  const {
    data: platforms,
    isLoading,
    refetch,
    isFetching,
  } = useQuery<Platform>(
    ["fetchPlatforms"],
    () => fetchData(`https://api.rawg.io/api/platforms?`),
    {
      refetchOnWindowFocus: false,
      staleTime: 1000000,
    }
  );
  console.log(platforms);
  const variants = {
    initial: {
      x: -1000,
      opacity: 0,
    },
    animate: {
      x: 0,
      opacity: 1,
    },
    exit: {
      opacity: 0,

      x: 1200,
    },
  };
  const small = useMediaQuery("(min-width:640px)");

  return (
    <div>
      <Head>
        <title>Platforms</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <div className="my-4 flex items-center justify-between px-4">
          <motion.button
            variants={variants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={{
              type: "string",
              damping: 10,
              stifness: 200,
            }}
            onClick={() => router.back()}
            className=" flex items-center gap-x-2 text-base xs:text-lg sm:text-2xl text-white"
          >
            <BiLeftArrow />
            {small ? <p>Back</p> : null}
          </motion.button>
          {router.isReady && (
            <motion.h1
              variants={variants}
              initial="initial"
              animate="animate"
              exit="exit"
              className="xs:text-xl text-lg sm:text-3xl font-black capitalize text-white md:text-5xl"
            >
              Platforms
            </motion.h1>
          )}
        </div>
        <div className="s grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {platforms?.results.map((platform) => (
            <PlatformCard key={v4()} platform={platform} />
          ))}
        </div>
      </Body>
    </div>
  );
};

export default PlatformsPage;
